from google.appengine.ext import ndb


class Parent(ndb.Model):
    """Model definition of a Parent"""
    first_name = ndb.StringProperty()
    last_name = ndb.StringProperty()
    # email should be unique, but we must not rely on it
    email = ndb.StringProperty(required=True)
    password = ndb.StringProperty(required=True)
    # this is the password generated by the system before the parent actually signs up
    temp_password = ndb.StringProperty()

    # Dwolla customer id
    customerId = ndb.StringProperty()
